### ISSUE TITLE
Lost icon in the section "Show all domains"

### ISSUE THREAD

**Issue by Lukashev-Danil** [Terrorhawk/Capri#14]
In the version of the skin OutServices, on the main page of the DA, in the section "Extra Features" icon has a link to the section hosting.da:2222/HTM_ALL_DOMAINS
And in your version of the skin, this link is missing. Can add it?

Thanks for your work!

![capri_old](https://cloud.githubusercontent.com/assets/14212118/9781399/9d05ea4c-57b5-11e5-8ac2-30b47545f4ae.JPG)
![capri_old_2](https://cloud.githubusercontent.com/assets/14212118/9781403/a59bb286-57b5-11e5-8989-d1571cea932c.JPG)
![capri_new](https://cloud.githubusercontent.com/assets/14212118/9781408/ac2e4a8c-57b5-11e5-82eb-0bdae9c22695.JPG)

**Comment by beliys** [comment]
Thank you for request, please update and check...
