### ISSUE TITLE
Home button tree in Show_All_Domains

### ISSUE THREAD

**Issue by Terrorhawk** [Terrorhawk/Capri#15]
Small bug:
In admin/all_domains.html 

|?TREE=&raquo; <a class=tree href="/HOME_MEMORY">`LANG_HOME`</a> &raquo; <a class=tree href="/HTM_ALL_DOMAINS">`LANG_ALL_DOMAINS_LIST`</a>|

HOME_MEMORY does not exist. it sould be /

**Comment by beliys** [comment]
fixed
