### ISSUE TITLE
Bug in additional_domains.html with NDOMAINSMAX evaluation

### ISSUE THREAD

**Issue by skaag** [Terrorhawk/Capri#16]
You need to fix this template to support packages with unlimited domains. In such pacakges, the NDOMAINSMAX variable is not numeric, it's a string with the value 'unlimited'.

At the moment you check |*if NDOMAINS<NDOMAINSMAX| which in the case of 'unlimited' domains will not work.

This means a customer with unlimited domains can not add a new domain. He gets an alert instead.

**Comment by beliys** [comment]
Thank you for bug report. Please update skin and check it again...
