### ISSUE TITLE
Catch-all

### ISSUE THREAD

**Issue by Killa-Bee** [Terrorhawk/Capri#17]
I am missing the catch-all button / option for e-mail settings !?!

**Comment by beliys** [comment]
Please, make screenshot for understanding problem...

**Comment by Killa-Bee** [comment]
Between the "POP3 E-mail Accounts" and "Forwarders" there should be a "Catch-All E-mail' button leading to /CMD_EMAIL_CATCH_ALL?DOMAIN=
![catchall](https://cloud.githubusercontent.com/assets/12719544/10520338/e8e0c818-7369-11e5-9188-ddb9eeb26146.gif)
![no-catchall](https://cloud.githubusercontent.com/assets/12719544/10520339/e8e16a34-7369-11e5-81a0-737a8ee61472.gif)

**Comment by beliys** [comment]
Thank you fir request and please update skin and check again...

**Comment by Killa-Bee** [comment]
Awsome working again !
